config/routes.rb
Rails.application.routes.draw do

  resources :genres
  root "movies#index"

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end
  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

  resources :users
  get "signup" => "users#new"
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  Copyright <em><%= Time.now.year %></em>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo.png"), root_path %>
    <ul class="left">
      <li>
        <%= nav_link_to "Released", movies_path %>
      </li>
      <li>
        <%= nav_link_to 'Upcoming', filtered_movies_path(:upcoming) %>
      </li>
      <li>
        <%= nav_link_to 'Recent', filtered_movies_path(:recent) %>
      </li>
      <li>
        <%= nav_link_to 'Hits', filtered_movies_path(:hits) %>
      </li>
      <li>
        <%= nav_link_to 'Flops', filtered_movies_path(:flops) %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to image_tag('gear.svg', size: 32),
                edit_user_path(current_user), hover: :none %>
        </li>
        <li>
          <%= link_to "Sign Out", session_path, method: :delete, class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", signin_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>